version: '3'

services:
  web: &python
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    container_name: djangoapp
    volumes:
      - ./app/:/usr/src/app/
      - ~/.aws/:/root/.aws:ro
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev-sample
    depends_on:
      - db
      - rabbitmq
      - celery_worker
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=database1_role
      - POSTGRES_PASSWORD=database1_password
      - POSTGRES_DB=database1

  rabbitmq:
    image: rabbitmq:3.7-alpine
  celery_worker:
    <<: *python
    container_name: celery
    command: celery -A accounts worker --loglevel=info
    ports: []
    depends_on:
      - rabbitmq
      - db
volumes:
  postgres_data:
